### ISSUE TITLE
how can I change the color of each polygon in stateful widget

### ISSUE THREAD

**Issue by bahiraei** [jozes/flutter_map_geojson#10]
I want to check whether my car is in the position of the polygon drawn on the map or not.
When the position of my car is inside the polygon, the color of the polygon becomes blue and when it leaves the polygon, it changes color to red

In short, how can I change the color of each polygon after the map is fully loaded?

**Comment by jozes** [comment]
Hi @bahiraei!
Colouring polygons after they are created is beyond the scope of this package and you should pose this question in flutter_map project. 

But before posting that question I would suggest you to check this package: https://pub.dev/packages/map_controller_plus, if it might help you. 

My approach would probably be to create a custom polygon creation function which would store all polygon data in a separate list. I would use the default createDefaultPolygon function as a template and create my own function.

```
  /// default callback function for creating [Polygon]
  Polygon createDefaultPolygon(List<LatLng> outerRing,
      List<List<LatLng>>? holesList, Map<String, dynamic> properties) {
    return Polygon(
      points: outerRing,
      holePointsList: holesList,
      borderColor: defaultPolygonBorderColor!,
      color: defaultPolygonFillColor!,
      isFilled: defaultPolygonIsFilled!,
      borderStrokeWidth: defaultPolygonBorderStroke!,
    );
  }
```



```
class MyPolygon {
  final List<LatLng> points;
  final List<List<LatLng>>? holePointsList;

  Color color;
  double borderStrokeWidth;
  Color borderColor;
  bool disableHolesBorder;
  bool isDotted;
  bool isFilled;
  StrokeCap strokeCap;
  StrokeJoin strokeJoin;
  String? label;
  final TextStyle labelStyle;
  final PolygonLabelPlacement labelPlacement;
  final bool rotateLabel;

 MyPolygon({
    required this.points,
    this.holePointsList,
    this.color = const Color(0xFF00FF00),
    this.borderStrokeWidth = 0.0,
    this.borderColor = const Color(0xFFFFFF00),
    this.disableHolesBorder = false,
    this.isDotted = false,
    this.isFilled = false,
    this.strokeCap = StrokeCap.round,
    this.strokeJoin = StrokeJoin.round,
    this.label,
    this.labelStyle = const TextStyle(),
    this.labelPlacement = PolygonLabelPlacement.centroid,
    this.rotateLabel = false,
  });
}
```

```
List<MyPolygon> myPolygonList = <MyPolygon>[];
 

  Polygon myPolygonCreationCallback(List<LatLng> outerRing,
      List<List<LatLng>>? holesList, Map<String, dynamic> properties) {
    myPolygonList.add(MyPolgon(points: outerRing,
      holePointsList: holesList,
      borderColor: defaultPolygonBorderColor!,
      color: defaultPolygonFillColor!,
      isFilled: defaultPolygonIsFilled!,
      borderStrokeWidth: defaultPolygonBorderStroke!,
    );
    return Polygon(
      points: outerRing,
      holePointsList: holesList,
      borderColor: defaultPolygonBorderColor!,
      color: defaultPolygonFillColor!,
      isFilled: defaultPolygonIsFilled!,
      borderStrokeWidth: defaultPolygonBorderStroke!,
    );
  }
```

Before returning a polygon I would add the same data to a List\<MyPolygon\>  where the painting parameters are not final. You have to inform geoJson parser about this custom creation function (change parser's initialization parameters). Then you can always change the colour of an arbitrary MyPolygon and create a new flutter_map Polygon from MyPolygon class and add only this Polygon to a separate PolygonLayer which you would paint on top of all other polygons. This PolygonLayer would always contain only one Polygon which is painted in your case in red colour. This way you don't need to touch the initial PolygonLayer and display it on top of other polygons. When required just recreate PolygonLayer with the polygon with red colour what is not a big deal. Unfortunately you have to store a "copy" of  all polygons data in List\<MyPolygon\> what is not a really  optimal solution. 

regards, Joze

**Comment by jozes** [comment]
I am closing this issue.
