### ISSUE TITLE
type 'int' is not a subtype of type 'double' in type cast

### ISSUE THREAD

**Issue by IgnacioHR** [jozes/flutter_map_geojson#14]
Hello!

Thanks for this code. I'm having an issue while reading some geojson. Here is a screen capture that documents the issue:

<img width="1206" alt="Window_y_geojson_parser_dart_—_dron_es" src="https://github.com/jozes/flutter_map_geojson/assets/16385090/03d787cf-95c3-46db-af0b-c5bae4f2ea4f">

As you can see, the selected point contains an int in the coordinates and the conversion assumes they are double value.

**Comment by jozes** [comment]
Hi @IgnacioHR,
I would need a short sample of your data in order to investigate the problem. I have no problem to parse coordinates 0, 0, so right now I can't reproduce your problem.
I would appreciate if you can also post the output of command "flutter doctor -v".
Regards, Joze

**Comment by IgnacioHR** [comment]
Hello and thank you for your response.

After some further investigation, the problem was in the conversion from stream (text) to json. That conversion was converting 0 to int and that was the source of the problem.

I've refactored my json parsers to make sure the values are all doubles and the GeoJsonParser now is able to deal with the data without issues.

I'm going to close this and hope this information help others in case they find similar issues with the initial json parsers.

Cheers,
Ignacio

**Comment by jozes** [comment]
@IgnacioHR,
Thanks for the update and I am glad that you have found the cause of the problem. 
Regards, Joze
