### ISSUE TITLE
How to get access to properties?

### ISSUE THREAD

**Issue by firszzz** [jozes/flutter_map_geojson#16]
I want to get the polygon properties even in string format. Is it possible to do this?

**Comment by jozes** [comment]
You can replace default functions which create markers, lines or polygon with your own functions. Just create them and specify them in parser setup.
These functions are defined as:

typedef MarkerCreationCallback = Marker Function(
    LatLng point, Map<String, dynamic> properties);
typedef CircleMarkerCreationCallback = CircleMarker Function(
    LatLng point, Map<String, dynamic> properties);
typedef PolylineCreationCallback = Polyline Function(
    List<LatLng> points, Map<String, dynamic> properties);
typedef PolygonCreationCallback = Polygon Function(List<LatLng> points,
    List<List<LatLng>>? holePointsList, Map<String, dynamic> properties);
typedef FilterFunction = bool Function(Map<String, dynamic> properties);

So write your own function (I name it here myPolygonCreationFunction) which accepts same parameters and then use it when you initialise parser:

 GeoJsonParser geoJsonParser = GeoJsonParser(
      defaultMarkerColor: Colors.red,
      defaultPolygonBorderColor: Colors.red,
      defaultPolygonFillColor: Colors.red.withOpacity(0.1),
      defaultCircleMarkerColor: Colors.red.withOpacity(0.25),
     /// define your function
      polygonCreationCallback: myPolygonCreationFunction;
  );   

 All these functions get properties as a map in their arguments. This way you will get direct access to properties which can be converted into the form you would like to have. You can then just call default creation function again or write your customised creation function. 

Hope this will help you to solve your problem.
Merry Christmas and a happy new year!
