### ISSUE TITLE
Does it support coordinates

### ISSUE THREAD

**Issue by Mahdi-Roozbahani** [jozes/flutter_map_geojson#18]
Hi, 

Thank you for the great library. 
I attached a complex Geojson, which also has coordinates and other types such as description and so on; do you think your library supports those?
[mygeodata.zip](https://github.com/jozes/flutter_map_geojson/files/14233654/mygeodata.zip)

**Comment by jozes** [comment]
It looks like a regular GeoJson. The properties contain some attributes like "Name" and  "description" which contains kind of a HTML encoded text. I think you can use this parser for displaying the contents of this file.  Juste be carefule 

"features": [
{ "type": "Feature", "properties": { "Name": "Faults", "description": "<a href=\"https:\/\/mrdata.usgs.gov\/geology\/state\/sgmc2-structure.php?id=54970\">Detailed description<\/a><\/p><p>Fault, sense of displacement unknown or undefined, certain<\/p><p><\/p>" },
"geometry": { "type": "MultiLineString", "coordinates": [ [ [ -72.82442968, 41.32537404 ], [ -72.82531825, 41.32245646 ] ] ] } },
...
...]
