### ISSUE TITLE
Filters missing

### ISSUE THREAD

**Issue by AtharvKinage** [jozes/flutter_map_geojson#2]
I need to filter data according to filter name. I cannot do it directly because the plugins directly parse the data

**Comment by SharmilaG2000** [comment]
How can I get geojson file for particular area of country or district.

**Comment by jozes** [comment]
@SharmilaG2000 
Probably I really don't understand your question. Besides some data sources which are publicly available most of the applications use the application geo-referenced data which is produced on demand from spatial data stored in various databases like Postgres, MySql, ....
In my opinion filtering data on client side is an option but far from being an optimal one. We are transferring more data across the internet which we subsequently filter out in application. My approach and I believe that the same approach is used by most of applications is that the spatial data is prepared on demand on the application backend according to the spatial  filter defined in the application and then there is no need to filter that data. Such approach not just reduces the amount of network transfer but also reduces the amount of memory used by application and reduces the required CPU cycles for processing that data.

**Comment by jozes** [comment]
@SharmilaG2000
The latest release of this package has now ability to filter out records according to the values present in the feature properties.
